version: '3.3'
services:
    db:
        image: postgres:13
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        volumes:
            - postgres_data:/var/lib/postgresql/data

    file_storage:
        image: filebrowser/filebrowser
        ports:
            - '8080:80'
        volumes:
            - ./file_storage:/srv
        environment:
            - FILEBROWSER_BASEURL=/filebrowser
            - FILEBROWSER_USER=admin
            - FILEBROWSER_PASSWORD=admin

volumes:
    postgres_data:
    file_storage:
