version: '3.3'
services:
    db:
        image: postgres:13
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
